---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.9.1 には、いくつかの新機能と機能拡張が含まれています。 
---
= Cloud Volumes ONTAP 9.9.1 の新機能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.9.1 には、いくつかの新機能と機能拡張が含まれています。

その他の機能と拡張機能も、最新バージョンのBlueXPで導入されました。を参照してください https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["BlueXPリリースノート"^] を参照してください。



== C4、M4、およびR4のインスタンスはサポートされなくなりました（2022年10月28日）

AWSでは、C4、M4、およびR4 EC2インスタンスタイプはCloud Volumes ONTAP でサポートされなくなりました。C4、M4、またはR4インスタンスタイプで実行されている既存のシステムがある場合は、C5、m5、またはr5インスタンスファミリーでインスタンスタイプに変更する必要があります。

link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-change-ec2-instance.html["Cloud Volumes ONTAP のEC2インスタンスタイプを変更する方法について説明します"^]。

を参照してください link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["ネットアップサポート"^] これらのインスタンスタイプの可用性とサポート終了の詳細については、を参照してください。



== 9.9.1 P8（2022年5月15日）

バージョン3.9.13以降を実行しているコネクタがある場合、Microsoft AzureでCloud Volumes ONTAP に対して9.9.1 P8パッチが利用できるようになりました。BlueXPでは、既存のシステムをこのパッチリリースにアップグレードするように求められます。

https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.9.1P8["P8 パッチで修正されたバグのリストを表示します"^] （ネットアップサポートサイトへのログインが必要です）。



== 9.9.1 P7 （ 2022 年 2 月 21 日）

バージョン 3.9.15 以降を実行しているコネクタがある場合、 Microsoft Azure で Cloud Volumes ONTAP に対して 9.9.1 P7 パッチが利用できるようになりました。BlueXPでは、既存のシステムをこのパッチリリースにアップグレードするように求められます。

https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.9.1P7["P7 パッチで修正されたバグのリストを表示します"^] （ネットアップサポートサイトへのログインが必要です）。



== 9.9.1 パッチ（ 2022 年 2 月 3 日）

Cloud Volumes ONTAP には、次の 2 つの新しいパッチがあります。

* 9.9.1 AWS と Google Cloud で P6 を使用
* 9.9.9.1 P3 ： Microsoft Azure


BlueXPでは、既存のシステムをこれらのパッチリリースにアップグレードするように求められます。

* https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.9.1P6["P6 パッチで修正されたバグのリストを表示します"^] （ネットアップサポートサイトへのログインが必要）
* https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.9.1P3["P3 パッチで修正されたバグのリストを表示します"^] （ネットアップサポートサイトへのログインが必要）




== 9.9.1 GA （ 2021 年 7 月 21 日）

Cloud Volumes ONTAP 9.9.1 の General Availability （ GA ）リリースがリリースされました。GA リリースにはバグの修正が含まれています。

BlueXPでは、9.9.1リリース候補、9.9..0、または9.8のいずれかのバージョンを実行している既存のシステムをアップグレードするように求められます。



== 9.9.1 アップデート（ 2021 年 7 月 7 日）

BlueXP 3.9.8リリースでは、次の変更が加えられました。

* Cloud Volumes ONTAP では、新しい充電方法を利用できます。
+
** * 容量ベースの BYOL * ：容量ベースのライセンスでは、 TiB あたりの Cloud Volumes ONTAP 料金を支払うことができます。ライセンスはネットアップアカウントに関連付けられており、ライセンスに十分な容量があるかぎり、複数の Cloud Volumes ONTAP システムを作成することができます。容量ベースのライセンスは、 _Essentials_or_Professional_ のいずれかのパッケージ形式で提供されます。
** * Freemium offering * ： Freemium により、ネットアップのすべての Cloud Volumes ONTAP 機能を無償で使用できます（クラウドプロバイダの料金は引き続き適用されます）。システムあたりの割り当て容量は 500 GiB に制限されており、サポート契約はありません。最大 10 個の Freemium システムを使用できます。
+
link:concept-licensing.html["これらのライセンスオプションの詳細については、こちらをご覧ください"]。



* AWS では、 Cloud Volumes ONTAP が m5dn.24xlarge インスタンスタイプをサポートするようになりました。料金には、 PAYGO Premium 、容量ベースのライセンス（ BYOL ）、ノードベースのライセンス（ BYOL ）があります。
* Google Cloud では、 Cloud Volumes ONTAP が Balanced Persistent Disk （ pd-bBalanced ）をサポートするようになりました。この SSD は、 GiB あたりの IOPS を下げて、パフォーマンスとコストのバランスを取ります。
* Google Cloud の新しい Cloud Volumes ONTAP システムでは、 custom-4-16384 マシンタイプはサポートされなくなりました。
+
このタイプのマシンで既存のシステムを実行している場合は、引き続き使用できますが、 n2 標準 -4 マシンタイプに切り替えることをお勧めします。



https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["BlueXPの新機能については、こちらをご覧ください"^]。



== 9.9.1 アップデート（ 2021 年 6 月 3 日）

最近のBlueXP 3.9.7リリースでは、新しいProfessionalパッケージのサポートが導入されました。このパッケージを使用すると、AWS Marketplaceから年間契約を結ぶことで、Cloud Volumes ONTAP とCloud Backup Service をバンドルできます。

link:reference-configs-aws.html["このライセンスオプションの詳細については、こちらをご覧ください。"]



== 9.9.1 Release Candidate （ 2021 年 5 月 24 日）

Cloud Volumes ONTAP 9.9.1 Release Candidate は、 AWS 、 Azure 、 Google Cloud Platform で提供されるようになりました。

で導入された機能に加えて https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["ONTAP 9.9.1"^]このリリースの Cloud Volumes ONTAP には、次の機能が含まれています。

* <<Azure での ONTAP S3 のサポート>>
* <<高速の書き込み速度で AWS のパフォーマンスが向上します>>
* <<IO2 ： AWS でブートディスクを使用します>>




=== Azure での ONTAP S3 のサポート

Azure の Cloud Volumes ONTAP から S3 オブジェクトストレージを提供できるようになりました。Cloud Volumes ONTAP for Microsoft Azure では、 NFS や SMB などの従来型のファイルベースプロトコルに加え、スケールアウトストレージのオプションとして S3 をサポートしています。

次の点に注意してください。

* Cloud Volumes ONTAP S3 と ONTAP の主なユースケースは、汎用のオブジェクトストアです。
* 現時点では、 AWS の Cloud Volumes ONTAP や Google Cloud では S3 プロトコルはサポートされていません。
* BlueXPには、ONTAP S3機能の管理機能はありません。


CLI を使用することが、 Cloud Volumes ONTAP からの S3 クライアントアクセスを設定するためのベストプラクティスです。詳細については、を参照してください http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-s3-cg/home.html["S3 構成パワーガイド"^]。



=== 高速の書き込み速度で AWS のパフォーマンスが向上します

Cloud Volumes ONTAP のスループットパフォーマンスが向上しました いつ https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-write-speed.html["高速の書き込み速度"^] サポートされているインスタンスタイプで有効になっている。



=== IO2 ： AWS でブートディスクを使用します

AWS では、新しい Cloud Volumes ONTAP システムのブートディスクがプロビジョニングされた IOPS SSD （ IO2 ）ボリュームになります。IO2 ボリュームは、以前はブートディスクに使用されていた io1 ボリュームよりも信頼性が高くなります。



== 必要なBlueXPコネクタのバージョン

新しいCloud Volumes ONTAP 9.9.1システムを導入し、既存のシステムを9.1.1にアップグレードするには、BlueXP Connectorのバージョン3.9.6以降が実行されている必要があります。



== アップグレードに関する注意事項

* Cloud Volumes ONTAP のアップグレードは、BlueXPから完了している必要があります。System Manager または CLI を使用して Cloud Volumes ONTAP をアップグレードしないでください。これを行うと、システムの安定性に影響を与える可能性
* 9.9.0 リリースおよび 9.8 リリースから Cloud Volumes ONTAP 9.9.1 にアップグレードできます。BlueXPでは、既存のCloud Volumes ONTAP 9.0/9.8システムを9.9.1リリースにアップグレードするように求められます。
+
http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html["BlueXPから通知があった場合のアップグレード方法について説明します"^]。

* シングルノードシステムのアップグレードでは、 I/O が中断されるまで最大 25 分間システムがオフラインになります。
* HA ペアのアップグレードは無停止で、 I/O が中断されません。無停止アップグレードでは、各ノードが連携してアップグレードされ、クライアントへの I/O の提供が継続されます。




=== DS3_v2 の場合

9.9.1 リリース以降では、 DS3_v2 VM タイプは新規および既存の Cloud Volumes ONTAP システムでサポートされなくなりました。この VM タイプで既存のシステムを実行している場合は、 9.9..1 にアップグレードする前に VM タイプを変更する必要があります。
